before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev


language: ruby
cache: bundler


language: php
php:
  - 5.5
  - 5.4
  - hhvm
script: phpunit Test.php

after_failure:

# blocklist
branches:
  except:
     - legacy



    